### PR TITLE
Added defaultIndex parameter to FluidNavBar.

### PR DESCRIPTION
**Pull request by Govorovdim**

### CODE REVIEW

**Comment by eric-taix** [comment]
Nice, thanks for this PR!  
BTW don't worry about the Dart CI / build, it always failed. 

Can you update the example and the README.md to reflect this change please?

**Comment by Govorovdim** [comment]
Thanks for looking into it.
Can you merge it then? =) 
I do not have rights to do that.

**Review by eric-taix — APPROVED** [review]
LGTM

**Comment by eric-taix** [comment]
Ooops didn't see that the version in pubspec.yaml must be changed. Can you set it to 1.1.1 ? Otherwise pub will reject it when publishing

**Comment by Govorovdim** [comment]
Done

**Review by eric-taix — APPROVED** [review]

**Pull request merged**
